When a file changes, jezebel was failing with the following:
  if (curr.mtime.getTime() !== prev.mtime.getTime()) {
                 ^
TypeError: Cannot call method 'getTime' of undefined
    at fileChanged (<path>\npm\node_modules\jezebel\lib\jezebel.js:34:18)
    at FSWatcher.<anonymous> (<path>\npm\node_modules\jezebel\lib\jezebel\watcher.js:42:61)
    at FSWatcher.emit (events.js:70:17)
    at FSEvent.onchange (fs.js:652:12)

This appears to have occurred because fs.watchFile is a deprecated function, replaced with fs.watch and the parameters are different for this new function.

Updated the appropriate files to handle the new parameters.